name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build & Push Image
      run: |    
      docker build . --file Dockerfile --tag chirag-emacs-image:v1
      echo "${{ secrets.DOCKERPW }}" | docker login -u "chirag314" --password-stdin
      docker image build -t chirag314/chirag-emacs-image:v1 .
      docker push chirag314/chirag-emacs-image:tagname
