name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
       docker build . --file Dockerfile --tag chirag-emacs-image:v1
       docker push chirag314/chirag-emacs-image:v1
